@startwbs
+_ note
*+_ api
**+_ SubmitNote (Facade Command)
**+_ NoteView (Read Model)
**+_ NotesView (Read Model)
*+_ core
**+_ Note (Aggregate)
**+_ CreateNote (Command)
**+_ UpdateNote (Command)
**+_ NoteMutated (Domain Event)
**+_ NoteIndexer (Process)
**+_ NoteRepository (Repository, Contract)
**+_ NoteViewRepository (Repository, Contract)
**+_ NotesViewRepository (Repository, Contract)
*+_ adapter-rest (driving adapter)
**+_ SubmitNoteHandler (Facade Command Handler)
*+_ adapter-amqp (driving adapter)
**+_ SubmitNoteHandler (Facade Command Handler)
*+_ adapter-rdbms (driven adapter)
**+_ NoteRepository (Repository, Realization)
*+_ adapter-nosql (driven adapter)
**+_ NoteViewRepository (Repository, Realization)
**+_ NotesViewRepository (Repository, Realization)
@endwbs
