@startuml
component note_app as "note-app"
component note_api as "note-api"
component note_core as "note-core"
component note_adapter_rest as "note-adapter-rest"
component note_adapter_amqp as "note-adapter-amqp"
component note_adapter_rdbms as "note-adapter-rdbms"
component note_adapter_nosql as "note-adapter-nosql"

note_api <.. note_core
note_api <.. note_adapter_rest
note_api <.. note_adapter_amqp
note_core <.. note_adapter_rdbms
note_core <.. note_adapter_nosql
note_adapter_rest <.. note_app
note_adapter_amqp <.. note_app
note_adapter_rdbms <.. note_app
note_adapter_nosql <.. note_app
@enduml