@startuml
' inclusions <1>
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/v13.0.0/distribution/eventstorming/single.puml

Command("CreateNote")
rectangle NoteFactory<<Factory>>
rectangle NoteRepository<<Repository>>
Aggregate("Note")

CreateNote ..> NoteFactory : 1. uses
CreateNote ..> NoteRepository : 2. uses

NoteFactory ..> Note : creates
NoteRepository ..> Note : persists
@enduml