@startuml
hide empty members

struct Core
struct DrivenAdapter as "Driven Adapter"
struct DrivingAdapter as "Driving Adapter"
struct Deliverable
struct Executable
struct Library
struct Client
struct API
struct Integration

API <.. Core
API <.. DrivingAdapter
API <.. Integration
Core <.. DrivenAdapter

Core <.. Deliverable
DrivingAdapter <.. Deliverable
DrivenAdapter <.. Deliverable
Integration <.. Deliverable

Deliverable <|-- Executable
Deliverable <|-- Library

DrivingAdapter <|-- Client
@enduml
